### PR TITLE
Use variadic version of QMetaMethod::invoke() on Qt 6.5 (closes #391)

### LINKED ISSUE #391: Qt 6.5 compatibility and broken QMetaMethod::invoke()
Trying to create a new Cutelyst application using Qt 6.5.1 I hit the following warning/error:

`QMetaMethod::invoke: cannot convert formal parameter 0 from Cutelyst::Context* in call to Root::Auto(Context*)`

This seems to be related to this Qt bug report: https://bugreports.qt.io/browse/QTBUG-105616

It stops calling the method. So trying to call a route results in an empty response.

Any idea how to solve this?

### PR DESCRIPTION
**Pull request by buschmann23**
Qt 6.5 introduced a new variadic version of QMetaMethod::invoke() that does not work with our current implementation. This adds a fast fix to use the new variadic version of QMetaMethod::invoke() on Qt 6.5+ but there might be better / more elegant approaches to fix the issue.

### CODE REVIEW

**Comment by dantti** [comment]
Thanks for the patch, this part of the code I've been planning on changing for a while, and now might be a good time.
In your PR you add the empty values to the list, but that is not needed because it was there for arg.value(x) do not crash.
This append of empty values isn't very expensive but causes args to detach and copy the strings, which are not copied due implicit shared, still it would be nicer to avoid the args detaching.
So my idea would be to have now 2 code paths, but basically doing the same, 
on setup we assign to std::function a lambda that has the required number of arguments, and have 8 options, like the switch but then we don't need the switch since the lambda will be only one.

I'm not sure this is faster than switch, because it might help with branch prediction, but in any case it would be better to safe-check the number of args and the required number of args, and then call it. What do you think?

File: Cutelyst/action.cpp [hunk 1]
```diff
@@ -207,6 +210,139 @@ bool Action::doExecute(Context *c)
...
+
+            ret = d->method.invoke(d->controller,
+                                   Qt::DirectConnection,
+                                   qReturnArg(methodRet),
+                                   c,
+                                   args);
+        } else {
+            QStringList args = c->request()->args();
+            // Fill the missing arguments
+            args.append(d->emptyArgs);
```
Comment (dantti) [inline Cutelyst/action.cpp:242]: remove this

File: Cutelyst/action.cpp [hunk 2]
```diff
@@ -207,6 +210,139 @@ bool Action::doExecute(Context *c)
...
+            QStringList args = c->request()->args();
+
+            ret = d->method.invoke(d->controller,
+                                   Qt::DirectConnection,
+                                   c,
+                                   args);
+        } else {
+            QStringList args = c->request()->args();
+            // Fill the missing arguments
+            args.append(d->emptyArgs);
```
Comment (dantti) [inline Cutelyst/action.cpp:303]: and this

**Review by dantti — COMMENTED** [review]
Let's do a quick fix now, just update the 2 uneeded parts, please add a check, an assert should do it to see if args.count() == method.paramcount(), and latter we improve this

**Comment by buschmann23** [comment]
Hmmm, replacing the filling of the arguments list by an assertion immediately triggers the assertion in all tests that use actions.

File: Cutelyst/action.cpp (hunk 1 above)
Comment (Danxomme) [reply Cutelyst/action.cpp:242]: Ok

File: Cutelyst/action.cpp (hunk 2 above)
Comment (Danxomme) [reply Cutelyst/action.cpp:303]: Ok

File: Cutelyst/action.cpp (hunk 1 above)
Comment (buschmann23) [reply Cutelyst/action.cpp:242]: @Danxomme No, not you. :) This was meant for me.

File: Cutelyst/action.cpp (hunk 2 above)
Comment (buschmann23) [reply Cutelyst/action.cpp:303]: @Danxomme No, not you. :) This was meant for me.

**Comment by buschmann23** [comment]
I could than look again into the proposed solution described in your comment [here](https://github.com/cutelyst/cutelyst/pull/392#issuecomment-1679373666) if I find more time or it. I already applied the current patch to my (open)SUSE packages so I can go on to work with it.

**Comment by dantti** [comment]
QList would be out of range and assert https://codebrowser.dev/qt5/qtbase/src/corelib/tools/qlist.h.html#_ZNK5QList2atEi

**Comment by buschmann23** [comment]
Yes, I know. But as we have the context as counted parameter for the called method, there is a mismatch between pure param and args count. If we can rely on that there is always a context object in the called method param list, we could do `Q_ASSERT(args.count() + 1 == d->method->parameterCount())`.

**Comment by buschmann23** [comment]
Ok, I now see that it only helps if the arguments count matches the expected parameter count. But if the tests (e.g. urifor-test02) put more arguments in as expected, the assertion fails again. I think we can not rely on current code that the arguments fit always as the current implementation tolerates the mismatch.

So, we could either stop the filling of the args list with empty values an accept the detaching, but using faster QList:at(), or remove the filling and use QList::value().

IMHO we should QList::value() as it will not create new QString if args count matches the expected params count.

File: Cutelyst/action.cpp (hunk 2 above)
Comment (Danxomme) [reply Cutelyst/action.cpp]: OK

**Comment by dantti** [comment]
pre-commit.ci run

**Comment by dantti** [comment]
pre-commit.ci run
